# Generated by Django 2.2.12 on 2020-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20201102_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clearance_period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
