# Generated by Django 2.2.12 on 2020-11-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='clearance_period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
