# Generated by Django 2.2.12 on 2020-11-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_transaction_clearance_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('clearance_period', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
