# Generated by Django 2.2.12 on 2020-11-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_clearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
